version: '3'
services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    links:
      - server
      - grafana
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.data/nginx/log:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d

  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./.data/db:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      PGDATA: /var/lib/postgresql/pgdata
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
    # ports:
    #   - 5432:5432

  server:
    build:
      context: ./server
    restart: unless-stopped
    labels:
      - autoheal=true
    depends_on:
      - db
    links:
      - db

  grafana:
    build:
      context: ./grafana
    restart: unless-stopped
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana_user
    depends_on:
      - db
    links:
      - db
