{
 "title": "Sample Bot Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "GroupBy", "query": "day, hour" }
  ]
 },
 "panels": [
  {
   "title": "전체 사용자",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM events\nWHERE\n  event = 'bot.end_user.created'"
    }
   ]
  },
  {
   "title": "전체 메시지",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM events\nWHERE\n  event IN ('bot.message.sent', 'bot.message.received')"
    }
   ]
  },
  {
   "title": "기간별 이벤트",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM events\nWHERE $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "기간별 신규 사용자",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM events\nWHERE \n  $__timeFilter(timestamp)\n  AND event = 'bot.end_user.created'"
    }
   ]
  },
  {
   "title": "기간별 활성 사용자",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT data#>>'{endUser, id}')\nFROM events\nWHERE \n  $__timeFilter(timestamp)\n  AND event IN ('bot.end_user.created', 'bot.end_user.updated')"
    }
   ]
  },
  {
   "title": "기간별 메시지",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM events\nWHERE \n  $__timeFilter(timestamp)\n  AND event IN ('bot.message.sent', 'bot.message.received')"
    }
   ]
  },
  {
   "title": "기간별 이벤트",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMPTZ_TRUNC('$GroupBy', timestamp, 'Asia/Seoul') AS time,\n  event,\n  COUNT(*) AS count\nFROM events\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY time, event\n\nUNION ALL\n\nSELECT\n  TIMESTAMPTZ_TRUNC('$GroupBy', timestamp, 'Asia/Seoul') AS time,\n  'total' AS event,\n  COUNT(*) AS count\nFROM events\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "기간별 사용자",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "WITH fullfill AS (\n  SELECT\n    TIMESTAMPTZ_TRUNC('$GroupBy', generate_series, 'Asia/Seoul') AS time,\n    0 AS cumulative,\n    0 AS new,\n    0 AS active\n  FROM GENERATE_SERIES(\n    $__timeFrom()::TIMESTAMPTZ,\n    $__timeTo()::TIMESTAMPTZ,\n    '1 $GroupBy'\n  )\n),\nresults AS (\n  SELECT\n    TIMESTAMPTZ_TRUNC('$GroupBy', timestamp, 'Asia/Seoul') AS time,\n    SUM(COUNT(DISTINCT CASE WHEN event IN ('bot.end_user.created', 'bot.end_user.updated') THEN data#>>'{endUser, id}' END)) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative,\n    COUNT(DISTINCT CASE WHEN event = 'bot.end_user.created' THEN data#>>'{endUser, id}' END) AS new,\n    COUNT(DISTINCT CASE \n        WHEN event = 'bot.message.received' THEN data#>>'{message, endUserId}'\n        WHEN event = 'bot.end_user.created' THEN data#>>'{endUser, id}'\n      END) AS active\n  FROM\n    events\n  WHERE\n    $__timeFilter(timestamp)\n    AND event IN ('bot.end_user.created', 'bot.end_user.updated', 'bot.message.received')\n  GROUP BY time\n)\nSELECT\n  COALESCE(r.time, f.time) AS time,\n  r.cumulative AS \"기간내 누적 사용자\",\n  COALESCE(r.new, f.new) AS \"신규 사용자\",\n  COALESCE(r.active, f.active) AS \"활성 사용자\"\nFROM fullfill f\n  LEFT JOIN results r ON f.time = r.time\n"
    }
   ]
  },
  {
   "title": "기간별 메시지",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "WITH fullfill AS (\n  SELECT\n    TIMESTAMPTZ_TRUNC('$GroupBy', generate_series, 'Asia/Seoul') AS time,\n    0 AS user_message,\n    0 AS bot_message,\n    0 AS agent_message\n  FROM GENERATE_SERIES(\n    $__timeFrom()::TIMESTAMPTZ,\n    $__timeTo()::TIMESTAMPTZ,\n    '1 $GroupBy'\n  )\n),\nresults AS (\n  SELECT\n    TIMESTAMPTZ_TRUNC('$GroupBy', timestamp, 'Asia/Seoul') AS time,\n    COUNT(CASE WHEN event = 'bot.message.received' THEN 1 END) AS user_message,\n    COUNT(CASE WHEN event = 'bot.message.sent' AND data#>>'{message, meta, persona}' IS NULL THEN 1 END) AS bot_message,\n    COUNT(CASE WHEN event = 'bot.message.sent' AND data#>>'{message, meta, persona}' IS NOT NULL THEN 1 END) AS agent_message\n  FROM\n    events\n  WHERE\n    $__timeFilter(timestamp)\n    AND event IN ('bot.message.received', 'bot.message.sent')\n  GROUP BY time\n)\nSELECT\n  COALESCE(r.time, f.time) AS time,\n  COALESCE(r.user_message, f.user_message) AS \"사용자 메시지\",\n  COALESCE(r.bot_message, f.bot_message) AS \"봇 메시지\",\n  COALESCE(r.agent_message, f.agent_message) AS \"상담원 메시지\"\nFROM fullfill f\n  LEFT JOIN results r ON f.time = r.time\n"
    }
   ]
  },
  {
   "title": "메시지",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  data#>>'{message, id}' AS id,\n  data#>>'{message, endUserId}' AS end_user_id,\n  data#>>'{message, conversationId}' AS conversation_id,\n  CASE\n    WHEN data#>>'{message, isUser}' = 'true' THEN 'user'\n    WHEN data#>>'{message, isUser}' = 'false' AND data#>>'{message, persona}' IS NOT NULL THEN 'agent'\n    ELSE 'bot'\n  END AS message_type,\n  data#>'{message, data}' AS data,\n  CAST(data#>>'{message, timestamp}' AS BIGINT) AS timestamp\nFROM events\nWHERE\n  event IN ('bot.message.sent', 'bot.message.received')\n  AND $__timeFilter(events.timestamp)\nORDER BY timestamp DESC"
    }
   ]
  }
 ]
}